In [5]:
import json
import pandas as pd


with open('AZ.min.json', 'r') as file:
    data = json.load(file)


zip_ids = [
    "85339", "85310", "85254", "85085", "85054", "85053", "85051", "85050", "85048", "85045",
    "85044", "85043", "85042", "85041", "85040", "85037", "85035", "85034", "85033", "85032",
    "85031", "85029", "85028", "85027", "85024", "85023", "85022", "85021", "85020", "85019",
    "85018", "85017", "85016", "85015", "85014", "85013", "85012", "85009", "85008", "85007",
    "85006", "85004", "85003"
]

In [9]:

filtered_data = {}
for feature in data['features']:
    zip_id = feature['properties']['ZCTA5CE10']
    if zip_id in zip_ids:
        # Assuming there's only one list of coordinates and removing one layer of nesting
        filtered_data[zip_id] = feature['geometry']['coordinates'][0]

rows = []
for zip_id in zip_ids:
    if zip_id in filtered_data:
        coordinates = filtered_data[zip_id]
        rows.append([zip_id, coordinates])
mapPLY = pd.DataFrame(rows, columns=['ZIP Code', 'Coordinates'])
mapPLY

   ZIP Code                                        Coordinates
0     85339  [[-112.12182, 33.377706], [-112.12113, 33.3777...
1     85310  [[-112.201113, 33.681783], [-112.201579, 33.68...
2     85254  [[-111.925599, 33.625778], [-111.925605, 33.62...
3     85085  [[-112.073978, 33.799033], [-112.073069, 33.79...
4     85054  [[-111.954227, 33.698731], [-111.953965, 33.69...
5     85053  [[-112.151137, 33.619755], [-112.151128, 33.62...
6     85051  [[-112.151429, 33.545707], [-112.151419, 33.54...
7     85050  [[-112.027452, 33.664476], [-112.027371, 33.66...
8     85048  [[-112.014138, 33.317971], [-112.013967, 33.31...
9     85045  [[-112.083527, 33.305138], [-112.083102, 33.30...
10    85044  [[-111.972387, 33.329411], [-111.972389, 33.32...
11    85043  [[-112.23844, 33.418736], [-112.23851, 33.4202...
12    85042  [[-112.073205, 33.363275], [-112.074635, 33.36...
13    85041  [[-112.075179, 33.375563], [-112.07518, 33.374...
14    85040  [[-111.999772, 33.420223], [-111.999778, 33.42...
15    85037  [[-112.272473, 33.47932], [-112.272471, 33.479...
16    85035  [[-112.195122, 33.462611], [-112.195756, 33.46...
17    85034  [[-112.065186, 33.428972], [-112.065195, 33.42...
18    85033  [[-112.237724, 33.504305], [-112.237722, 33.50...
19    85032  [[-111.992515, 33.597071], [-111.995084, 33.59...
20    85031  [[-112.171982, 33.480483], [-112.172259, 33.48...
21    85029  [[-112.116543, 33.610849], [-112.115722, 33.61...
22    85028  [[-112.036122, 33.563611], [-112.036193, 33.56...
23    85027  [[-112.117124, 33.654677], [-112.117568, 33.65...
24    85024  [[-112.048601, 33.725637], [-112.048556, 33.72...
25    85023  [[-112.116543, 33.610893], [-112.116506, 33.61...
26    85022  [[-112.060698, 33.607645], [-112.060946, 33.60...
27    85021  [[-112.112269, 33.549253], [-112.112286, 33.55...
28    85020  [[-112.073859, 33.569559], [-112.073852, 33.57...
29    85019  [[-112.151498, 33.526148], [-112.151485, 33.52...
30    85018  [[[-111.995179, 33.531838], [-111.995813, 33.5...
31    85017  [[-112.122348, 33.538553], [-112.121739, 33.53...
32    85016  [[-112.047655, 33.486399], [-112.049546, 33.48...
33    85015  [[-112.112955, 33.487744], [-112.112955, 33.48...
34    85014  [[-112.066308, 33.503788], [-112.067336, 33.50...
35    85013  [[-112.073703, 33.527057], [-112.073702, 33.52...
36    85012  [[-112.068867, 33.538299], [-112.067893, 33.53...
37    85009  [[-112.099932, 33.465877], [-112.099971, 33.46...
38    85008  [[-112.006294, 33.451285], [-112.008458, 33.45...
39    85007  [[-112.100003, 33.437643], [-112.100006, 33.43...
40    85006  [[-112.063958, 33.480204], [-112.06064, 33.480...
41    85004  [[-112.073789, 33.44424], [-112.07379, 33.445]...
42    85003  [[-112.082478, 33.443849], [-112.082479, 33.44...

In [ ]:

mapPLY.to_csv('mapPLY.csv', index=False)